spring.application.name=e-commerce
# Enable Java 21 Virtual Threads
spring.threads.virtual.enabled=true
server.port=8081
# Kafka Settings
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Database (H2 for easy testing)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# This setting is critical for Spring Boot 4+
spring.h2.console.settings.web-allow-others=true

# Ensure the DB name matches what you type in the login box
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This shows the SQL in your IntelliJ console so we can see the inserts!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Change this line:
spring.datasource.url=jdbc:h2:file:./data/orderdb;DB_CLOSE_DELAY=-1




# Tells Spring how to turn your Java Strings into Kafka bytes
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer


# Kafka Consumer Settings
spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.properties.spring.json.add.type.headers=false